### ISSUE TITLE
Customise items in the embed widget

### ISSUE THREAD

**Issue by karthikb351** [hasgeek/boxoffice#166]
There is an increasing use case for allowing the boxoffice widget to only show a subset of items in an item collection, as well as define the order of items.

- A workshop might exist as part of a conference's item collection for accounting/organizing purposes but have its own page and marketing, in which case you want just to workshop ticket to be sold on that page
- One off events can exist as part of a general item collection (say Open House), but only have the relevant ticket shown on event's page
- A/B testing will be easier as you can just swap configs

### Possible implementation
Pass a list of item ids in the widget's config, the widget can filter them and render only them in same order.

```javascript
window.Boxoffice.init({
    org: '', // Organization to show
    paymentDesc: '', // Description for payments widget
    itemCollection: '', // ItemCollection ID to show
    items: [] // Array of Item IDs
});
```

**Comment by shreyas-satish** [comment]
This was implemented in https://github.com/hasgeek/boxoffice/pull/167.
