### ISSUE TITLE
Aggregate Reports

### ISSUE THREAD

**Issue by mediatinker** [hasgeek/boxoffice#195]
Aggregate reports are useful for forecasting and reporting and significantly easier than clicking into each dashboard one by one and jotting down numbers, which is how I do it now.

In an ideal solution, there would be a flexible report interface that allows the user to select a reporting period (i.e. this month, last month, date-to-date) and the data desired (all or specific events, ticket quantities, sales, averages, etc)

In a less ideal solution, there would be a set of standard reports for various use cases.

**Comment by anandvenkatanarayanan** [comment]
This is no longer required. Hence closing it.
