### ISSUE TITLE
company name and twitter handle missing for my badge

### ISSUE THREAD

**Issue by captn3m0** [hasgeek/boxoffice#209]
Happened for the second conference this time (50p). 

Email confirmation includes the company name and the twitter handle

![image](https://user-images.githubusercontent.com/584253/35955293-82a9d580-0cb4-11e8-8774-68f925ee39ca.png)

But the badge doesn't have it. I checked the form that I filled, and it has the right details as well:

![image](https://user-images.githubusercontent.com/584253/35955315-a9d157f0-0cb4-11e8-8346-0ec417b8bf11.png)

Badge

![image](https://user-images.githubusercontent.com/584253/35955381-060f69f8-0cb5-11e8-8e3f-bef0da90cb32.png)

**Comment by shreyas-satish** [comment]
This is a bug with the check-in system which is currently hosted on [funnel](https://github.com/hasgeek/funnel). Moving this issue there.

Thank you for reporting this.
