### ISSUE TITLE
Annotation for each 'Item'

### ISSUE THREAD

**Issue by akshaybhalotia** [hasgeek/boxoffice#231]
For each item (or at least order), there should be a field for free-form annotation. Annotations could be as many in number and should be displayed with a timestamp and username.
Primary use for this is adding notes about the purchase or the buyer, which can be used for internal purposes (such as improving targeting), upselling for other events and ticket management (additional requests, special cases, etc).

**Comment by anandvenkatanarayanan** [comment]
This is no longer required. Can be revisited if this is required at a later point in time.
