### ISSUE TITLE
Need assignee details on order API

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [hasgeek/boxoffice#262]
The API /organization/hasgeek/order/:order_id provides the following JSON: 
```json
{
   "final_amount" : 100,
   "line_items" : [
   ],
   "title" : "Title",
   "receipt_no" : 300,
   "refunds" : [],
   "status" : "Sales Order",
   "invoices" : [
   ],
   "order_id" : "order_id"
}
```

Typically invoices section is not filled which makes it difficult to use this API for emailing participants. The above API needs the latest assignee details, so that it looks like this: 

```json
{
   "final_amount" : 100,
   "line_items" : [
   ],
   "title" : "Title",
   "receipt_no" : 300,
   "refunds" : [],
   "status" : "Sales Order",
   "invoices" : [
   ],
   "order_id" : "order_id",
   "assignee": {
      "Name": "name",
      "email": "email",
      "phone": "phone-number"
   }
}
```

**Comment by jace** [comment]
We track buyer separately from assignee, as our typical use case is managers buying for team members. Buyer name, email and phone are collected at the time of purchase (unlike assignee, which is after purchase). Buyer info can be exposed in the API.

**Comment by anandvenkatanarayanan** [comment]
An automated system to generate invoices, must know without manual intervention, who to send the invoices to. The use case for invoice generation is for either reimbursement or for claiming tax credits. So exposing both these parties in the API will work, as it is easier to add them in the To list.
