### ISSUE TITLE
GST Invoice Options

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [hasgeek/boxoffice#301]
### Background
There are 2 types of GST Invoices: 

1. B2B invoices where the buyer and seller are both businesses (Business to Business) and
2. B2C invoices where the buyer is a retail consumer. 

The distinguishing factor between these two invoices is that only businesses have a GST number. Currently Box office provides the following information as part of the invoices section:
```json
"invoices" : [
      {
         "city" : "Hyderabad",
         "status" : "Draft",
         "invoiced_at" : "Thu, 20 Jun 2019 05:44:29 GMT",
         "street_address_2" : null,
         "state_code" : "TG",
         "invoice_no" : 20000,
         "country_code" : "IN",
         "street_address_1" : "Address",
         "invoicee_company" : "XYZ",
         "buyer_taxid" : null,
         "state" : null,
         "invoicee_email" : "name@XYZ.com",
         "seller_taxid" : null,
         "postcode" : "500032"
      }
```

The key field to note is the buyer_taxid. If it is null, then it is a B2C invoice or it contains a valid GST#, then it is a B2B invoice.  B2B invoices are thus always issued in the name of the company (invoicee_company) and B2C invoices are always issued in the name of the individual who bought it. 

### Reimbursements
Field experience indicates that most of the participants don't fill the GST#  in the invoice section, but do fill the invoicee_company name properly. This presents a problem in issuing invoices because to claim reimbursements from their employers, participants need the company name in the invoices and also their names. So there is a need to distinguish the reimbursement case correctly in the UI and also report it in the invoices JSON (reimbursement: true or equivalent) as shown below: 

```json
"invoices" : [
      {
         "city" : "Hyderabad",
         "status" : "Draft",
         "invoiced_at" : "Thu, 20 Jun 2019 05:44:29 GMT",
         "street_address_2" : null,
         "state_code" : "TG",
         "invoice_no" : 20000,
         "country_code" : "IN",
         "street_address_1" : "Address",
         "invoicee_company" : "XYZ",
         "buyer_taxid" : null,
         "state" : null,
         "invoicee_email" : "name@XYZ.com",
         "seller_taxid" : null,
         "postcode" : "500032", 
         "reimbursement": true
      }
```

While the exact semantics might not be the same as reported above, what is clear is the need to handle reimbursement as a separate item in the B2C invoice case.

**Comment by vidya-ram** [comment]
Fixing this as part of PR #297
Adding invoicee_name to order json endpoint https://github.com/hasgeek/boxoffice/pull/297/files#diff-5673641a6ec0df93317e4cbb5e6cdaa6R145

When a person fills their name (invoicee_name) and company name(invoicee_company) but  leaves the GSTIN(buyer_taxid) empty, we could issue B2C in the invoicee_name.
