### ISSUE TITLE
Post more useful stats via Slack webhook

### ISSUE THREAD

**Issue by sindhus** [hasgeek/boxoffice#33]
At the moment, the slack webhook integration (added in [commit 354c8e3](https://github.com/hasgeek/boxoffice/commit/354c8e37b39a4a46ec6f584f6f943808770e4680)) posts stats of count of tickets sold and cancelled. These stats are rudimentary and don't give a statistical view of how well or bad the sales are doing for an event.

Ideally, these stats are required: 
(a) headcount on each day
(b) the revenue and revenue velocity (rate of sales) and 
(c) order count and velocity.

Before implementing these, one needs to address if Boxoffice has anything to indicate premium conf ticket and regular conf ticket are tickets to the same event?

**Comment by jace** [comment]
Every item has dates attached, so dates are a cheap proxy for items being related.

This will not work in a scenario where we sell separate per-track tickets for the same day. But we aren't there yet.

**Comment by shreyas-satish** [comment]
Closing this for now since posting stats to Slack was removed in https://github.com/hasgeek/boxoffice/commit/cb343d81df5a2fdf034ec3a3793eae49b178c607
