### ISSUE TITLE
Unable to use a particular email from the account in the ticket details

### ISSUE THREAD

**Issue by kracekumar** [hasgeek/boxoffice#336]
I have purchased a ticket for [`SQL Masterclass` workshop](https://hasgeek.com/rootconf/sql-masterclass/). After the purchase, on the workshop page, the widget showed a button to fill `attendee details`. On clicking the button, the new tab opened up with the form to fill the attendee details. I filled all the mandatory form fields and entered the email address `foo@email.com`. When I submitted the form, the email field displayed the error message, `Email address has been already used`. This is the email, I used while making the payment. I got an email to fill the attendee details to same email address(but the field was empty when the link opened up).

My account has three email ids - `foo@email.com, bar@example.com, baz@some.com`. `bar@example.com` is the primary email address in the [HasGeek Account page](https://hasgeek.com/account). 

The attendee details email field doesn't complain when I enter `bar@example.com` and the submit succeeded. Now, I go back to the HasGeek account and change my primary email address to `foo@email.com` and modify the email in the attendee details page, again same error throws up, `Email address has been already used`. 

In case, you need the receipt number, I'm happy to share it.

Note: I merged all three email addresses a few hours before purchasing the ticket.

**Comment by jace** [comment]
I think this has been resolved via #319 back in August. @kracekumar please re-open if you encounter this again.
