### ISSUE TITLE
Shopping cart for a more intuitive buying experience.

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/boxoffice#62]
Some users have found it hard to figure out what they need to do, after adding an item. 

![fe_bo](https://cloud.githubusercontent.com/assets/380688/16517485/3e76d24c-3f9b-11e6-845c-caa53f5f50bc.jpg)

After adding a conference ticket, the user is thinking - 'Okay, what do I do next?'.

I propose the following. The widget should show a floating shopping cart that appears after adding an item. The cart should give the user a quick overview of what's been added and should also provide a button to help fast forward the user to the checkout process.

**Comment by jace** [comment]
I don't think a UI hack is the answer. This widget is fundamentally uninspired and needs a ground up rethink of how the event is sold to the user.
